add secrets to AWS secret manager

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,14 +43,22 @@ jobs:
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    - name: Fetch Secret from AWS Secrets Manager
-      id: fetch_secret  
+    - name: Fetch Secret
       run: | 
         aws configure set default.debug true
-        SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id jl-testing --query SecretString --output text) || exit 1  # Make it fail explicitly
-        echo "Retrieved Secret Value (if successful):" $SECRET_VALUE   
-        echo "::add-mask::$SECRET_VALUE"
-        echo "::set-output name=secret_value::$SECRET_VALUE" "  
+        MAX_ATTEMPTS=3
+        CURRENT_ATTEMPT=1
+        while [ $CURRENT_ATTEMPT -le $MAX_ATTEMPTS ]; do
+          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id jl-testing --query SecretString.serverless_db_password --output text) || exit 1
+          if [[ -n "$SECRET_VALUE" ]]; then
+            echo "Retrieved Secret Value:" $SECRET_VALUE 
+            echo "::add-mask::$SECRET_VALUE"
+            echo "::set-output name=secret_value::$SECRET_VALUE"
+            break
+          fi
+          sleep 5s  # Wait 5 seconds before retry
+          CURRENT_ATTEMPT=$(( CURRENT_ATTEMPT + 1 ))
+        done
     - name: Use secret in code 
       run: |
         echo "The secret value is: ${MY_SECRET}" 
